-- MySQL Script generated by MySQL Workbench
-- sam. 10 juin 2017 23:34:50 GMT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema francophonie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema francophonie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `francophonie` DEFAULT CHARACTER SET utf8 ;
USE `francophonie` ;

-- -----------------------------------------------------
-- Table `francophonie`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `francophonie`.`admin` (
  `id` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `contact` VARCHAR(45) NULL,
  `lastlogin` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `francophonie`.`universite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `francophonie`.`universite` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `francophonie`.`filiere`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `francophonie`.`filiere` (
  `id` INT NOT NULL,
  `code` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `francophonie`.`document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `francophonie`.`document` (
  `id` INT NOT NULL,
  `theme` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `auteur` VARCHAR(45) NULL,
  `annee` INT NULL,
  `filiere_id` INT NOT NULL,
  `universite_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  PRIMARY KEY (`id`, `universite_id`),
  INDEX `fk_document_filiere_idx` (`filiere_id` ASC),
  INDEX `fk_document_universite1_idx` (`universite_id` ASC),
  INDEX `fk_document_admin1_idx` (`admin_id` ASC),
  CONSTRAINT `fk_document_filiere`
    FOREIGN KEY (`filiere_id`)
    REFERENCES `francophonie`.`filiere` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_universite1`
    FOREIGN KEY (`universite_id`)
    REFERENCES `francophonie`.`universite` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_document_admin1`
    FOREIGN KEY (`admin_id`)
    REFERENCES `francophonie`.`admin` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
